In [ ]:
#Numpy
import numpy as np

List Vs Numpy-Time

In [ ]:
from time import process_time
pythonList=[i for i in range(10000)]
Start_time=process_time()
python_list=[i+5 for i in pythonList]
end_time=process_time()
print(end_time-Start_time)

0.0011995049999997676


In [ ]:
np_array=np.array([i for i in range(10000)])
start_time=process_time()
np_array+=5
end_time=process_time()
print(end_time-start_time)

0.00014548500000000075


Data Types NUMERICAL

1. int-numpy.integer
2. float64-numpy.float64
3. Boolean-numpy.bool
4. Complex-numpy.complex128

The above can be used with python object for dtype and the interpreter understands it.
5. unit(unsigned Integer)

STRING AND BYTES

1. numpy.str_
2. numpy.bytes_
3. numpy.void

The above are called fixed-width data types. They have a fixed width within which the single data element has to fit inside(either in unicode points and bytes)

In [ ]:
#Checking
q=np.array([(1,2,3,4),(5,6,7,8)])
np.issubdtype(q.dtype,np.integer)

True

In [ ]:
q=np.array([1,2,3,4,5])
np.issubdtype(q.dtype,np.float_)

False

In [ ]:
#String datatype
t=np.array(["Hello","world"], dtype='U6')#Maximum of 6 code points (If shorter or longer datatype is specified then it is either Zero-padded or truncated)
print(t)
#Bytes datatype
u=np.array(["Hello","world"],dtype="S7").tobytes()#Missing palces are filled with \x00
print(u)
#Difference between stored trailing arrays and padded arrays
xy = [b"hello\0\0", b"world"]
yx = np.array(xy, dtype="S7")
print(yx[0])
print(xy[0]==yx[0])
#Void DataTypes
l=np.array(xy,dtype="V7")#array([b'\x68\x65\x6C\x6C\x6F\x00\x00', b'\x77\x6F\x72\x6C\x64\x00\x00'],dtype='|V7')
print(l)
print(l[0]==np.void(xy[0]))



['Hello' 'world']
b'Hello\x00\x00world\x00\x00'
b'hello'
False
[b'\x68\x65\x6C\x6C\x6F\x00\x00' b'\x77\x6F\x72\x6C\x64\x00\x00']
True


Advanced DataTypes: Structured Arrays. It is similar to structs in C

In [ ]:
data = np.array([('A', 10, 99.0), ('B', 15, 96.0)],
             dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])
print(data)
print(data['name'])
#If name not assigned, it creates default name as f0,f1 or f2 based on order
print(np.dtype('3int8,float32,(2,3)float64'))
#As Dictionary
np.dtype({'names':['col1','col2'],
          'formats':['i4','f4'],
          'offsets':[0,4],
          'itemsize':12})



[('A', 10, 99.) ('B', 15, 96.)]
['A' 'B']
[('f0', 'i1', (3,)), ('f1', '<f4'), ('f2', '<f8', (2, 3))]


dtype({'names': ['col1', 'col2'], 'formats': ['<i4', '<f4'], 'offsets': [0, 4], 'itemsize': 12})

Numpy Arrays

In [ ]:
list1=[1,2,3,4,5] #List
print(list1)
print(type(list1))
np_array=np.array([1,2,3,4,5])
print(np_array)
print(type(np_array))# nd-n-dimensional
print(np_array.shape)#no of rows and no of columns

[1, 2, 3, 4, 5]
<class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


Array creation

In [ ]:
#2 Dimensional
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)
print(b.shape)
#Float
c=np.array([(1,2,3),(5,6,7)],dtype=float)
print(c)



[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1. 2. 3.]
 [5. 6. 7.]]


Initial Placeholders in Numpy arrays

In [ ]:
#Initial values present in numpy arrays
x=np.zeros((4,5))
print(x)
y=np.ones((3,3))
print(y)
#array of particular number
z=np.full((5,4),5)
print(z)
#create an identity matrix
d=np.eye(4)
print(d)
#Create numpy array with randon values
e=np.random.random((3,4))
print(e)#values are between 0 and 1. Generates different values at each time
#Numpy array with random integers within specific range
f=np.random.randint(1,60,(3,3))
print(f)
#Array of evenly spaced Values
g=np.linspace(10,30,6)
print(g)
#Another Method for array of evenly spaced values
h=np.arange(10,30,5)# here 5 is step size and not number of values
print(h)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.1482853  0.74539652 0.83211654 0.36014722]
 [0.85456622 0.94346704 0.02586409 0.20004662]
 [0.81866105 0.07033324 0.87215755 0.17964424]]
[[ 9 31 20]
 [26 25 15]
 [ 6 35 44]]
[10. 14. 18. 22. 26. 30.]
[10 15 20 25]


Convert list to numpy array

In [ ]:
list2=[10,20,30,40,50]
print(list2)
print(type(list2))
np_array2=np.asarray(list2)
print(np_array2)
print(type(np_array2))

[10, 20, 30, 40, 50]
<class 'list'>
[10 20 30 40 50]
<class 'numpy.ndarray'>


Same code for changing tuple to numpy array

Analysing Numpy Array

In [ ]:
n=np.random.randint(10,90,(5,5))
print(n)

[[64 47 40 34 24]
 [12 40 58 33 41]
 [80 29 10 80 41]
 [22 17 61 20 78]
 [37 14 17 11 10]]


In [ ]:
#Array Dimension
print(n.shape)
#Number of Dimensions
print(n.ndim)
#Number of elements
print(n.size)
#Checking the datatype
print(n.dtype)

(5, 5)
2
25
int64


Mathematical Operations on an Numpy array

In [ ]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
print(list1+list2) #Concatenate or join two lists

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
np_a=np.random.randint(0,10,(3,3))
np_b=np.random.randint(10,20,(3,3))
print(np_a)
print(np_b)
print(np_a + np_b)
print(np_a - np_b)
print(np_a * np_b)
print(np_a / np_b)

[[9 6 7]
 [2 7 7]
 [8 8 3]]
[[10 10 18]
 [19 10 19]
 [16 12 10]]
[[19 16 25]
 [21 17 26]
 [24 20 13]]
[[ -1  -4 -11]
 [-17  -3 -12]
 [ -8  -4  -7]]
[[ 90  60 126]
 [ 38  70 133]
 [128  96  30]]
[[0.9        0.6        0.38888889]
 [0.10526316 0.7        0.36842105]
 [0.5        0.66666667 0.3       ]]


In [ ]:
#Other method
np1=np.random.randint(0,10,(3,3))
np2=np.random.randint(10,20,(3,3))
print(np1)
print(np2)
print(np.add(np1,np2))
print(np.subtract(np1,np2))
print(np.multiply(np1,np2))
print(np.divide(np1,np2))


[[5 3 7]
 [7 0 0]
 [1 1 2]]
[[13 17 10]
 [19 17 18]
 [12 14 11]]
[[18 20 17]
 [26 17 18]
 [13 15 13]]
[[ -8 -14  -3]
 [-12 -17 -18]
 [-11 -13  -9]]
[[ 65  51  70]
 [133   0   0]
 [ 12  14  22]]
[[0.38461538 0.17647059 0.7       ]
 [0.36842105 0.         0.        ]
 [0.08333333 0.07142857 0.18181818]]


Array Manipulation

In [ ]:
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)
#Transpose
trans=np.transpose(array)
print(trans)
print(trans.shape)
#Another method
trans2=array.T
print(trans2)
print(trans2.shape)

[[3 6 3]
 [0 3 0]]
(2, 3)
[[3 0]
 [6 3]
 [3 0]]
(3, 2)
[[3 0]
 [6 3]
 [3 0]]
(3, 2)


In [ ]:
#Reshaping Numpy Array
ab=np.random.randint(0,10,(2,3))
print(ab)
print(ab.shape)
cd=np.reshape(ab,(3,2))
print(cd)
print(cd.shape)

[[3 8 2]
 [2 1 2]]
(2, 3)
[[3 8]
 [2 2]
 [1 2]]
(3, 2)


Other Basic Functions

In [ ]:
w=np.arange(16).reshape(4,4)
print(w)
#Add Reduce
print(np.add.reduce(w,1))
print(np.add.reduce(w,(0,1)))
#Multiply Reduce
print(np.multiply.reduce(w,1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 6 22 38 54]
120
[    0   840  7920 32760]


Statistics

In [ ]:
#Sum
print(w.sum(axis=0))
#Minimum
print(w.min(axis=0))
#Maximun
print(w.max(axis=0))
#Mean
print(w.mean(axis=0))
#Variance
print(w.var(axis=1))
#Standard deviation
print(w.std(axis=1))
#median
print(np.median(w,axis=0))
#Average
print(np.average(w,axis=1))
#Sorting
print(w.sort(axis=0))
#2dHistogram
print(np.histogram2d(w.flatten(),w.flatten()))


[24 28 32 36]
[0 1 2 3]
[12 13 14 15]
[6. 7. 8. 9.]
[1.25 1.25 1.25 1.25]
[1.11803399 1.11803399 1.11803399 1.11803399]
[6. 7. 8. 9.]
[ 1.5  5.5  9.5 13.5]
None
(array([[2., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 2., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 2., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 2., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 2., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 2.]]), array([ 0. ,  1.5,  3. ,  4.5,  6. ,  7.5,  9. , 10.5, 12. , 13.5, 15. ]), array([ 0. ,  1.5,  3. ,  4.5,  6. ,  7.5,  9. , 10.5, 12. , 13.5, 15. ]))


Other functions are np.ptp(Max-min), percentile, nanpercentile, quantile, nanquantile,nanmedian,nanmean,nanvar,nanstd,corrcoef,cov,correlate,histogram,histogramdd,bincount,histogram_bin_edges,digitalize etc

***POLYNOMIALS***

In [ ]:
from numpy.polynomial import Polynomial as poly1d
#Polynomial with coefficients
p=np.poly1d([1,2,3])
print(p)
#Polynomial with roots
r=np.poly([-1,1])
q=np.poly1d(r)
print(q)
#Polynomial with degree
x=np.arange(10)
y=np.arange(10)+np.arange(10)
z=np.poly1d(np.polyfit(x,y,3))
print(z)


   2
1 x + 2 x + 3
   2
1 x - 1
           3             2
3.457e-17 x - 6.312e-16 x + 2 x - 5.336e-15


Other functions are polyadd,polymul,polysub,polydiv,polyder,polyint